### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TimeSeries'

### ISSUE THREAD

**Issue by shanmenaka96** [akloster/python-mindwave#9]
I'm trying to use MindWave mobile with Windows Python.But python-mindwave module generates below error.Can anyone please help? Thank you!

  

>   E ====================================================================== ERROR: testParser (main.ParserTests) ---------------------------------------------------------------------- Traceback (most recent call last): File "C:\Users\shan\Desktop\python-mindwave-master\test\tests.py", line 9, in testParser ts_recorder = TimeSeriesRecorder() File "C:\Python27\lib\site-packages\mindwave\parser.py", line 139, in init self.meditation = pd.TimeSeries() AttributeError: 'module' object has no attribute 'TimeSeries'
> 
>     ---------------------------------------------------------------------- Ran 1 test in 0.034s
> 
>     FAILED (errors=1)
> 
>

**Comment by akloster** [comment]
It's because the Pandas TimeSeries class has been deprecated. You can either set up a virtualenv with a much older Pandas (don't know which), or update the code to use DataFrame.

I'm not actively maintaining this code, but would consider merging a pull request.
